name: Star reminder
  run: 
    echo "If this project helps you, please star it:"
    echo "https://github.com/yan2anfei/bmp_display_tools"

name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make  check
      run: make  check
    - name: make  distcheck
      run: make  distcheck
